---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
# OUT OF SAMPLE
# IN SAMPLE
# MODEL COMPARISION
# INTERPRETATION - also check p-values
# LDA
# QDA

library(caret)
library(doParallel)
```

```{r}
cl <- makeCluster(detectCores())
registerDoParallel(cl)
```


```{r}
#dat <- readRDS("../Dataset/Data_Cleansed.rds")
dat <- readRDS("../Dataset/Data_CE_Filtered.rds")
datCopy <- dat
datCopy$name <- NULL
```

datCopy$market_1 <- factor(datCopy$market_1)# OUT OF SAMPLE PREDICTION
##### Need to balance the imbalance dataset first!

```{r}
# post_success
'%ni%' <- Negate('%in%')  # define 'not in' func
options(scipen=999)  # prevents printing scientific notations.

# Prep Training and Test data.
set.seed(100)
trainDataIndex <- createDataPartition(datCopy$post_success, p=0.7, list = F)  # 70% training data
trainData <- datCopy[trainDataIndex, ]
testData <- datCopy[-trainDataIndex, ]
table(trainData$post_success)
```


```{r}
# Down Sample
set.seed(100)
down_train <- upSample(x = trainData[, colnames(trainData) %ni% "post_success"],
                         y = trainData$post_success)

table(down_train$Class)
colnames(down_train)[which(names(down_train) == "Class")] <- "post_success"
```

```{r}
str(down_train)
```


```{r}
# Run algorithms using 5-fold cross validation
fitControl <- trainControl(method="cv", number= 10, allowParallel = TRUE)
```



```{r}
knn_fit <- train(post_success ~ ., data = down_train, method="knn", trControl=fitControl)
```

```{r}
print(knn_fit)
```

```{r}
plot(knn_fit)
```

```{r}
predictions <- predict(knn_fit, testData)
confusionMatrix(predictions, testData$post_success)
```



```{r}
stopCluster(cl)
```




