---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
# OUT OF SAMPLE
# IN SAMPLE
# MODEL COMPARISION
# INTERPRETATION - also check p-values
# LDA
# QDA

library(caret)
library(doParallel)
```

```{r}
cl <- makeCluster(detectCores())
registerDoParallel(cl)
```


```{r}
dat <- readRDS("/Users/vineethpenugonda/Documents/Academics/Masters/Semester IV/IST 5535/Projects/StartUps_Investments_ML/Dataset/Data_CE_Filtered.rds")
datCopy <- dat
```

# OUT OF SAMPLE PREDICTION
##### Need to balance the imbalance dataset first!

```{r}
# post_success
'%ni%' <- Negate('%in%')  # define 'not in' func
options(scipen=999)  # prevents printing scientific notations.

# Prep Training and Test data.
set.seed(100)
trainDataIndex <- createDataPartition(datCopy$post_success, p=0.7, list = F)  # 70% training data
trainData <- datCopy[trainDataIndex, ]
testData <- datCopy[-trainDataIndex, ]
table(trainData$post_success)
```

```{r}
# Down Sample
set.seed(100)
down_train <- upSample(x = trainData[, colnames(trainData) %ni% "post_success"],
                         y = trainData$post_success)

table(down_train$Class)
colnames(down_train)[which(names(down_train) == "Class")] <- "post_success"
```

```{r}
## Train a logistic regression model with 10-fold cross-validation
fitControl <- trainControl(method = "cv",number = 10)

set.seed(100)
logit_fit <- train(post_success ~ ., data = down_train,
                   trControl = fitControl,
                   method="glm", family=binomial(link='logit'))
```

```{r}
print(logit_fit)
```

```{r}
# In-sample performance
confusionMatrix(logit_fit)
```

```{r}
# Out-of-sample performance
confusionMatrix(predict(logit_fit, newdata = testData),
                testData$post_success, positive = '1')
```


```{r}
stopCluster(cl)
```



