---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, echo=FALSE}
library(dplyr)
library(ggplot2)
```

# Read File
```{r}
dat <- readRDS("../Dataset/Data_Cleansed.rds")
str(dat)
```

# Visualisation

```{r}
# Heatmap 
# TBD
```


```{r}
##### GRAPHS ########

# Founding year
dat %>% count(founded_year)%>% arrange(-n) %>% head(25) %>%
  ggplot(aes(reorder(founded_year, n), n)) + geom_col(aes(fill=founded_year)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Year Founded") + xlab("Year") + ylab("Count") +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "Facebook")) +
  geom_text(aes(x = founded_year, y=2000, label = "Facebook"), data = dat %>% filter(name == "Facebook"), size=4, vjust=-0.3, hjust=-0.3) +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "Twitter")) +
  geom_text(aes(x = founded_year, y=2000, label = "Twitter"), data = dat %>% filter(name == "Twitter"), size=4, vjust=-0.3, hjust=-0.3) +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "Google")) +
  geom_text(aes(x = founded_year, y=2000, label = "Google"), data = dat %>% filter(name == "Google"), size=4, vjust=-0.3, hjust=-0.3) +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "YouTube")) +
  geom_text(aes(x = founded_year, y=2000, label = "YouTube"), data = dat %>% filter(name == "YouTube"), size=4, vjust=-0.3, hjust=-0.3) +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "Instagram")) +
  geom_text(aes(x = founded_year, y=2000, label = "Instagram"), data = dat %>% filter(name == "Instagram"), size=4, vjust=-0.3, hjust=-0.3) +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "Uber")) +
  geom_text(aes(x = founded_year, y=2000, label = "Uber,"), data = dat %>% filter(name == "Uber"), size=4, vjust=-0.3, hjust=0.6) +
  geom_vline(aes(xintercept = founded_year), data = dat %>% filter(name == "WhatsApp")) +
  geom_text(aes(x = founded_year, y=2000, label = "WhatsApp"), data = dat %>% filter(name == "WhatsApp"), size=4, vjust=-0.3, hjust=-0.3)
```

```{r}
# State Code
dat %>% count(state_code)%>% arrange(-n) %>% head(20) %>%
  ggplot(aes(reorder(state_code, n), n)) + geom_col(aes(fill=state_code)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of startups in States") + xlab("States") + ylab("Count")
```

```{r}
# Startups since 2000
dat %>% filter(founded_year>1999) %>% count(founded_year)%>% arrange(-n) %>% 
 ggplot(aes(founded_year, n), n) + geom_col(aes(fill=founded_year)) + 
 theme(legend.position="none") + 
 ggtitle("Year Founded") + xlab("Year") + ylab("Count") + 
 theme(axis.text.x=element_text(angle=40))
```

```{r}
# Top 10 market leaders
dat %>% filter(market!="") %>% count(market)%>% arrange(-n) %>% head(10) %>%
 ggplot(aes(reorder(market, n), n)) + geom_col(aes(fill=market)) + coord_flip() +
 theme(legend.position="none") +
 ggtitle("Top 10 Market Leaders") + xlab("Markets") + ylab("Count")
```

```{r}
# Markets
dat %>% count(market)%>% arrange(-n) %>% head(30) %>%
  ggplot(aes(reorder(market, n), n)) + geom_col(aes(fill=market)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of Startups in Different Markets") + xlab("Markets") + ylab("Count")
```

```{r}
# Regions
dat %>% count(region)%>% arrange(-n) %>% head(20) %>%
  ggplot(aes(reorder(region, n), n)) + geom_col(aes(fill=region)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of Startups in Region") + xlab("Regions") + ylab("Count")
```

```{r}
# Cities
dat %>% count(city)%>% arrange(-n) %>% head(30) %>%
  ggplot(aes(reorder(city, n), n)) + geom_col(aes(fill=city)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of Startups in Cities") + xlab("Cities") + ylab("Count")
```

```{r}
# No. of Startups vs Status
dat %>% count(status)%>% arrange(-n) %>%
  ggplot(aes(reorder(status, n), n)) + geom_col(aes(fill=status))  +
  theme(legend.position="none") +
  ggtitle("No. of Startups vs Status") + xlab("Status") + ylab("Count")
```

```{r}
# No. of Startups vs Status: PIE
dat %>% count(status)%>% arrange(-n) %>%
  ggplot(aes(reorder(status, n), n, fill=status))  + geom_bar(stat="identity", width=1) +
  theme(legend.position="none") + coord_polar("y", start=0) +
  ggtitle("No. of Startups vs Status") + xlab("Status") + ylab("Count")
```


```{r}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library(stringr)
```


```{r}
docs <- apply(dat['category_list'], 2, function(y) str_sub(y, 2, -2))
docs <- apply(docs, 2, function(y) unlist(strsplit(y, "\\|")))
docs <- Corpus(VectorSource(docs))
```

```{r}
#inspect(docs)
```

```{r}
#toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
#docs <- tm_map(docs, toSpace, "/")
#docs <- tm_map(docs, toSpace, "+")
#docs <- tm_map(docs, toSpace, "\\|")
```

```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
#docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
#docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
```

```{r}
#inspect(docs)
```


```{r}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
```

```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

```{r}
#Explore frequent terms and their associations
#You can have a look at the frequent terms in the term-document matrix as follow. In the example below we want to find words that occur at least four times :
findFreqTerms(dtm, lowfreq = 4)
```

```{r}
findAssocs(dtm, terms = "health", corlimit = 0.3)
```

```{r}
#The frequency table of words
head(d, 10)
```

```{r}
#Plot word frequencies
barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Most frequent words",
        ylab = "Word frequencies")
```

