---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, echo=FALSE}
library(dplyr)
library(ggplot2)
```

# Read File
```{r}
dat <- readRDS("/Users/vineethpenugonda/Documents/Academics/Masters/Semester IV/IST 5535/Projects/StartUps_Investments_ML/Dataset/Data_Cleansed.rds")
str(dat)
```

# Visualisation

```{r}
# Heatmap 
# TBD
```


```{r}
##### GRAPHS ########

# Founding year
dat %>% count(founded_year)%>% arrange(-n) %>% head(25) %>%
  ggplot(aes(reorder(founded_year, n), n)) + geom_col(aes(fill=founded_year)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Year Founded") + xlab("Year") + ylab("Count")
```

```{r}
# State Code
dat %>% count(state_code)%>% arrange(-n) %>% head(20) %>%
  ggplot(aes(reorder(state_code, n), n)) + geom_col(aes(fill=state_code)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of startups in States") + xlab("States") + ylab("Count")
```

```{r}
# Startups since 2000
dat %>% filter(founded_year>1999) %>% count(founded_year)%>% arrange(-n) %>% 
 ggplot(aes(founded_year, n), n) + geom_col(aes(fill=founded_year)) + 
 theme(legend.position="none") + 
 ggtitle("Year Founded") + xlab("Year") + ylab("Count") + 
 theme(axis.text.x=element_text(angle=40))
```

```{r}
# Top 10 market leaders
dat %>% filter(market!="") %>% count(market)%>% arrange(-n) %>% head(10) %>%
 ggplot(aes(reorder(market, n), n)) + geom_col(aes(fill=market)) + coord_flip() +
 theme(legend.position="none") +
 ggtitle("Top 10 Market Leaders") + xlab("Markets") + ylab("Count")
```

```{r}
# Markets
dat %>% count(market)%>% arrange(-n) %>% head(30) %>%
  ggplot(aes(reorder(market, n), n)) + geom_col(aes(fill=market)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of Startups in Different Markets") + xlab("Markets") + ylab("Count")
```

```{r}
# Regions
dat %>% count(region)%>% arrange(-n) %>% head(20) %>%
  ggplot(aes(reorder(region, n), n)) + geom_col(aes(fill=region)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of Startups in Region") + xlab("Regions") + ylab("Count")
```

```{r}
# Cities
dat %>% count(city)%>% arrange(-n) %>% head(30) %>%
  ggplot(aes(reorder(city, n), n)) + geom_col(aes(fill=city)) + coord_flip() +
  theme(legend.position="none") +
  ggtitle("Number of Startups in Cities") + xlab("Cities") + ylab("Count")
```

```{r}
# No. of Startups vs Status
dat %>% count(status)%>% arrange(-n) %>%
  ggplot(aes(reorder(status, n), n)) + geom_col(aes(fill=status))  +
  theme(legend.position="none") +
  ggtitle("No. of Startups vs Status") + xlab("Status") + ylab("Count")
```

```{r}
# No. of Startups vs Status: PIE
dat %>% count(status)%>% arrange(-n) %>%
  ggplot(aes(reorder(status, n), n, fill=status))  + geom_bar(stat="identity", width=1) +
  theme(legend.position="none") + coord_polar("y", start=0) +
  ggtitle("No. of Startups vs Status") + xlab("Status") + ylab("Count")
```

